// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0M-dtkifwB6hiJX8NKWMnKVerF7iBRTc',
    appId: '1:538421062157:web:1751a84baafa71ff300344',
    messagingSenderId: '538421062157',
    projectId: 'chatapp-76cc5',
    authDomain: 'chatapp-76cc5.firebaseapp.com',
    storageBucket: 'chatapp-76cc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsn7WwXjyX7d8ONzP4WxZOkmFFB4rb62E',
    appId: '1:538421062157:android:0fe1b3c9c29aa7fe300344',
    messagingSenderId: '538421062157',
    projectId: 'chatapp-76cc5',
    storageBucket: 'chatapp-76cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9AysSLKHv5f9xw5r9bCg5of3wjusxWU',
    appId: '1:538421062157:ios:373e04eecbeb6287300344',
    messagingSenderId: '538421062157',
    projectId: 'chatapp-76cc5',
    storageBucket: 'chatapp-76cc5.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9AysSLKHv5f9xw5r9bCg5of3wjusxWU',
    appId: '1:538421062157:ios:373e04eecbeb6287300344',
    messagingSenderId: '538421062157',
    projectId: 'chatapp-76cc5',
    storageBucket: 'chatapp-76cc5.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0M-dtkifwB6hiJX8NKWMnKVerF7iBRTc',
    appId: '1:538421062157:web:3b70e5f6f2f1c84b300344',
    messagingSenderId: '538421062157',
    projectId: 'chatapp-76cc5',
    authDomain: 'chatapp-76cc5.firebaseapp.com',
    storageBucket: 'chatapp-76cc5.appspot.com',
  );
}
